In [2]:
import pandas as pd

dataframe = pd.read_csv('Churn_Modelling.csv')

In [3]:
dataframe

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

## dropping rownumber, customerID and surname(first three columns) , as they do not add meaning to the data.

In [4]:
dataframe.drop(['RowNumber', 'CustomerId', 'Surname'], axis = 1, inplace=True)


In [5]:
dataframe

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [6]:
def get_unique_values(df):
    for col in df.columns:
        print(col)
        unique_val = df[col].unique()
        print(unique_val)
        print(col , 'total unique values:',len(unique_val))
        print()

In [7]:
get_unique_values(dataframe)

CreditScore
[619 608 502 699 850 645 822 376 501 684 528 497 476 549 635 616 653 587
 726 732 636 510 669 846 577 756 571 574 411 591 533 553 520 722 475 490
 804 582 472 465 556 834 660 776 829 637 550 698 585 788 655 601 656 725
 511 614 742 687 555 603 751 581 735 661 675 738 813 657 604 519 664 678
 757 416 665 777 543 506 493 652 750 729 646 647 808 524 769 730 515 773
 814 710 413 623 670 622 785 605 479 685 538 562 721 628 668 828 674 625
 432 770 758 795 686 789 589 461 584 579 663 682 793 691 485 650 754 535
 716 539 706 586 631 717 800 683 704 615 667 484 480 578 512 606 597 778
 514 525 715 580 807 521 759 516 711 618 643 671 689 620 676 572 695 592
 567 694 547 594 673 610 767 763 712 703 662 659 523 772 545 634 739 771
 681 544 696 766 727 693 557 531 498 651 791 733 811 707 714 782 775 799
 602 744 588 747 583 627 731 629 438 642 806 474 559 429 680 749 734 644
 626 649 805 718 840 630 654 762 568 613 522 737 648 443 640 540 460 593
 801 611 802 745 483 690 492 709 705 56

## checking if estimatedSalary have zero entry or not ? because if estimatedSalary is zero than the respective record is invalidated. 

In [8]:
def check_zero_entry_on_float_column(col):
    unique_items = dataframe[col].unique()
    print(unique_items)
    print(len(unique_items))

    check = False
    for idx , val in enumerate(unique_items):
        if val == 0.0:
            check = True
            print('There is zero entry at index as follows:')
            print(idx)
            print(val)
    if check == False:
        print('There is no Zero Entry in column :' , col)

In [9]:
check_zero_entry_on_float_column('EstimatedSalary')

[101348.88 112542.58 113931.57 ...  42085.58  92888.52  38190.78]
9999
There is no Zero Entry in column : EstimatedSalary


##  balance feature can have 0 entry , in this case it makes sense because every salary feature is filled. 

In [10]:
check_zero_entry_on_float_column('Balance')

[     0.    83807.86 159660.8  ...  57369.61  75075.31 130142.79]
6382
There is zero entry at index as follows:
0
0.0


## linear scaling CreditScore , Age and Balance and estimatedSalary Column.

In [11]:
dfscaled = dataframe.copy()
columns = ['CreditScore' , 'Age' , 'Balance' , 'EstimatedSalary']
for col in columns:
    dfscaled[col] = (dfscaled[col] - dfscaled[col].min()) / (dfscaled[col].max() - dfscaled[col].min())    
    
# lineartly normalized
display(dfscaled)

CreditScore Geography  Gender       Age  Tenure   Balance  \
0           0.538    France  Female  0.324324       2  0.000000   
1           0.516     Spain  Female  0.310811       1  0.334031   
2           0.304    France  Female  0.324324       8  0.636357   
3           0.698    France  Female  0.283784       1  0.000000   
4           1.000     Spain  Female  0.337838       2  0.500246   
...           ...       ...     ...       ...     ...       ...   
9995        0.842    France    Male  0.283784       5  0.000000   
9996        0.332    France    Male  0.229730      10  0.228657   
9997        0.718    France  Female  0.243243       7  0.000000   
9998        0.844   Germany    Male  0.324324       3  0.299226   
9999        0.884    France  Female  0.135135       4  0.518708   

      NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0                 1          1               1         0.506735       1  
1                 1          0               1         0.562709       0  
2                 3          1               0         0.569654       1  
3                 2          0               0         0.469120       0  
4                 1          1               1         0.395400       0  
...             ...        ...             ...              ...     ...  
9995              2          1               0         0.481341       0  
9996              1          1               1         0.508490       0  
9997              1          0               1         0.210390       1  
9998              2          1               0         0.464429       1  
9999              1          1               0         0.190914       0  

[10000 rows x 11 columns]

# converting categorical values to quantitative values

### as we know there are only 3 unique values in geography column hence,
### 0 - > France , 1 - > Spain, 2 - > Germany

### as we know there are only 2 unique values in gender column hence,
### 0 - > Male  ,1 - > Female

In [12]:
for idx ,val in dfscaled.iterrows():
    if  dfscaled.loc[idx,'Gender'] == 'Male':
        dfscaled.loc[idx,'Gender'] = '0'
    elif dfscaled.loc[idx,'Gender'] == 'Female':
        dfscaled.loc[idx,'Gender'] = '1'
        
for idx ,val in dfscaled.iterrows():
    if  dfscaled.loc[idx,'Geography'] == 'France':
        dfscaled.loc[idx,'Geography'] = '0'
    elif dfscaled.loc[idx,'Geography'] == 'Spain':
        dfscaled.loc[idx,'Geography'] = '1'
    elif dfscaled.loc[idx,'Geography'] == 'Germany':
        dfscaled.loc[idx,'Geography'] = '2'

In [13]:
dfscaled

CreditScore Geography Gender       Age  Tenure   Balance  NumOfProducts  \
0           0.538         0      1  0.324324       2  0.000000              1   
1           0.516         1      1  0.310811       1  0.334031              1   
2           0.304         0      1  0.324324       8  0.636357              3   
3           0.698         0      1  0.283784       1  0.000000              2   
4           1.000         1      1  0.337838       2  0.500246              1   
...           ...       ...    ...       ...     ...       ...            ...   
9995        0.842         0      0  0.283784       5  0.000000              2   
9996        0.332         0      0  0.229730      10  0.228657              1   
9997        0.718         0      1  0.243243       7  0.000000              1   
9998        0.844         2      0  0.324324       3  0.299226              2   
9999        0.884         0      1  0.135135       4  0.518708              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1         0.506735       1  
1             0               1         0.562709       0  
2             1               0         0.569654       1  
3             0               0         0.469120       0  
4             1               1         0.395400       0  
...         ...             ...              ...     ...  
9995          1               0         0.481341       0  
9996          1               1         0.508490       0  
9997          0               1         0.210390       1  
9998          1               0         0.464429       1  
9999          1               0         0.190914       0  

[10000 rows x 11 columns]

## applying softmax on NumOfProducts , as it will reduce the scale to 1. 
### unique values are 1 , 2 , 3 , 4 

In [14]:
import math
sum_of_exp = 0
for i in range(1,5):
    sum_of_exp =  sum_of_exp + math.exp(i)
    
print(sum_of_exp)

for idx ,val in dfscaled.iterrows():
    if  dfscaled.loc[idx,'NumOfProducts'] == 1:
        dfscaled.loc[idx,'NumOfProducts'] = (math.exp(1)/(sum_of_exp))
    elif dfscaled.loc[idx,'NumOfProducts'] == 2:
        dfscaled.loc[idx,'NumOfProducts'] = (math.exp(2)/(sum_of_exp))
    elif  dfscaled.loc[idx,'NumOfProducts'] == 3:
        dfscaled.loc[idx,'NumOfProducts'] = (math.exp(3)/(sum_of_exp))
    elif dfscaled.loc[idx,'NumOfProducts'] == 4:
        dfscaled.loc[idx,'NumOfProducts'] = (math.exp(4)/(sum_of_exp))

84.7910248837216


In [15]:
dfscaled

CreditScore Geography Gender       Age  Tenure   Balance  NumOfProducts  \
0           0.538         0      1  0.324324       2  0.000000       0.032059   
1           0.516         1      1  0.310811       1  0.334031       0.032059   
2           0.304         0      1  0.324324       8  0.636357       0.236883   
3           0.698         0      1  0.283784       1  0.000000       0.087144   
4           1.000         1      1  0.337838       2  0.500246       0.032059   
...           ...       ...    ...       ...     ...       ...            ...   
9995        0.842         0      0  0.283784       5  0.000000       0.087144   
9996        0.332         0      0  0.229730      10  0.228657       0.032059   
9997        0.718         0      1  0.243243       7  0.000000       0.032059   
9998        0.844         2      0  0.324324       3  0.299226       0.087144   
9999        0.884         0      1  0.135135       4  0.518708       0.032059   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1         0.506735       1  
1             0               1         0.562709       0  
2             1               0         0.569654       1  
3             0               0         0.469120       0  
4             1               1         0.395400       0  
...         ...             ...              ...     ...  
9995          1               0         0.481341       0  
9996          1               1         0.508490       0  
9997          0               1         0.210390       1  
9998          1               0         0.464429       1  
9999          1               0         0.190914       0  

[10000 rows x 11 columns]

In [16]:
get_unique_values(dfscaled)

CreditScore
[0.538 0.516 0.304 0.698 1.    0.59  0.944 0.052 0.302 0.668 0.356 0.294
 0.252 0.398 0.57  0.532 0.606 0.474 0.752 0.764 0.572 0.32  0.638 0.992
 0.454 0.812 0.442 0.448 0.122 0.482 0.366 0.406 0.34  0.744 0.25  0.28
 0.908 0.464 0.244 0.23  0.412 0.968 0.62  0.852 0.958 0.574 0.4   0.696
 0.47  0.876 0.61  0.502 0.612 0.75  0.322 0.528 0.784 0.674 0.41  0.506
 0.802 0.462 0.77  0.622 0.65  0.776 0.926 0.614 0.508 0.338 0.628 0.656
 0.814 0.132 0.63  0.854 0.386 0.312 0.286 0.604 0.8   0.758 0.592 0.594
 0.916 0.348 0.838 0.76  0.33  0.846 0.928 0.72  0.126 0.546 0.64  0.544
 0.87  0.51  0.258 0.67  0.376 0.424 0.742 0.556 0.636 0.956 0.648 0.55
 0.164 0.84  0.816 0.89  0.672 0.878 0.478 0.222 0.468 0.458 0.626 0.664
 0.886 0.682 0.27  0.6   0.808 0.37  0.732 0.378 0.712 0.472 0.562 0.734
 0.9   0.666 0.708 0.53  0.634 0.268 0.26  0.456 0.324 0.512 0.494 0.856
 0.328 0.35  0.73  0.46  0.914 0.342 0.818 0.332 0.722 0.536 0.586 0.642
 0.678 0.54  0.652 0.444 0.69  0.484 0.43

## checking data type of all the attributes

In [17]:
result = dfscaled.dtypes
print(result)

CreditScore        float64
Geography           object
Gender              object
Age                float64
Tenure               int64
Balance            float64
NumOfProducts      float64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object


## changing objects to int64

In [18]:
import numpy as np
dfscaled['Geography'] = dfscaled['Geography'].astype(str).astype(np.int64)
dfscaled['Gender'] = dfscaled['Gender'].astype(str).astype(np.int64)

In [19]:
result = dfscaled.dtypes
print(result)

CreditScore        float64
Geography            int64
Gender               int64
Age                float64
Tenure               int64
Balance            float64
NumOfProducts      float64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object


In [20]:
X = dfscaled.drop('Exited', axis = 1)
Y = dfscaled['Exited']

In [21]:
X = np.asarray(X)
Y = np.asarray(Y)

print(X)
print(Y)

[[0.538      0.         1.         ... 1.         1.         0.50673489]
 [0.516      1.         1.         ... 0.         1.         0.56270874]
 [0.304      0.         1.         ... 1.         0.         0.56965435]
 ...
 [0.718      0.         1.         ... 0.         1.         0.21039009]
 [0.844      2.         0.         ... 1.         0.         0.46442905]
 [0.884      0.         1.         ... 1.         0.         0.19091423]]
[1 0 1 ... 1 1 0]


In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=42)
print(type(X_train))
print(type(Y_train))
print(type(X_test))
print(type(Y_test))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [23]:
print(len(X_train))
print(len(X_train[0]))
print(len(Y_train))
print(Y_train)

print('-------------------------\n')

print(len(X_test))
print(len(X_test[0]))
print(len(Y_test))
print(Y_test)


6700
10
6700
[1 0 1 ... 1 1 0]
-------------------------

3300
10
3300
[0 0 0 ... 0 0 1]


In [24]:
import keras
def model(x_train, x_test, y_train, y_test):
    mod = keras.Sequential([
        keras.layers.Dense(1500, input_dim = len(x_train[0]), activation = 'relu'),
        keras.layers.Dense(700, activation = 'relu'),
        keras.layers.Dense(1, activation = 'sigmoid'),
    ])
    
    mod.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics = ['accuracy']
    )
    
    mod.fit(x_train, y_train, epochs=110)
    
    print(f'\n test accuracy -> {mod.evaluate(x_test, y_test)}')

    y_pred = mod.predict(x_test)
    y_pred = np.round(y_pred)
    
    return y_pred


In [25]:
y_pred = model(X_train, X_test, Y_train, Y_test)

Epoch 1/110
210/210 [==============================] - 3s 12ms/step - loss: 0.4812 - accuracy: 0.7916
Epoch 2/110
210/210 [==============================] - 2s 11ms/step - loss: 0.4501 - accuracy: 0.8069
Epoch 3/110
210/210 [==============================] - 2s 12ms/step - loss: 0.4302 - accuracy: 0.8210
Epoch 4/110
210/210 [==============================] - 2s 11ms/step - loss: 0.4240 - accuracy: 0.8212
Epoch 5/110
210/210 [==============================] - 2s 11ms/step - loss: 0.4185 - accuracy: 0.8240
Epoch 6/110
210/210 [==============================] - 3s 13ms/step - loss: 0.4130 - accuracy: 0.8290
Epoch 7/110
210/210 [==============================] - 3s 13ms/step - loss: 0.4026 - accuracy: 0.8339
Epoch 8/110
210/210 [==============================] - 3s 12ms/step - loss: 0.3995 - accuracy: 0.8357
Epoch 9/110
210/210 [==============================] - 3s 13ms/step - loss: 0.3942 - accuracy: 0.8390
Epoch 10/110
210/210 [==============================] - 2s 12ms/step - loss: 0.390

210/210 [==============================] - 3s 12ms/step - loss: 0.1863 - accuracy: 0.9216
Epoch 80/110
210/210 [==============================] - 3s 13ms/step - loss: 0.1834 - accuracy: 0.9196
Epoch 81/110
210/210 [==============================] - 3s 15ms/step - loss: 0.1855 - accuracy: 0.9199
Epoch 82/110
210/210 [==============================] - 3s 13ms/step - loss: 0.1822 - accuracy: 0.9237
Epoch 83/110
210/210 [==============================] - 2s 11ms/step - loss: 0.1794 - accuracy: 0.9236
Epoch 84/110
210/210 [==============================] - 3s 12ms/step - loss: 0.1742 - accuracy: 0.9249
Epoch 85/110
210/210 [==============================] - 3s 14ms/step - loss: 0.1717 - accuracy: 0.9258
Epoch 86/110
210/210 [==============================] - 2s 10ms/step - loss: 0.1727 - accuracy: 0.9281
Epoch 87/110
210/210 [==============================] - 2s 10ms/step - loss: 0.1720 - accuracy: 0.9245
Epoch 88/110
210/210 [==============================] - 2s 10ms/step - loss: 0.1646 - 

In [26]:
print(y_pred)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [1.]]


## classification report

In [27]:
#Evaluating the prediction
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      0.90      0.89      2657
           1       0.55      0.51      0.53       643

    accuracy                           0.82      3300
   macro avg       0.72      0.71      0.71      3300
weighted avg       0.82      0.82      0.82      3300

